name: Scrape Windows ISO Links

on:
  # Schedule: Run daily at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run scraper
        run: |
          python scraper.py

      - name: Check if JSON changed
        id: check_changes
        run: |
          git add windows_iso_links.json
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "No changes detected in windows_iso_links.json"
          else
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "Changes detected in windows_iso_links.json"
          fi

      - name: Commit and push if changed
        if: steps.check_changes.outputs.changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Update Windows ISO links - ${{ github.run_id }}

          Co-Authored-By: Claude <noreply@anthropic.com>"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          file_pattern: "windows_iso_links.json"
          push_options: '--force'
          skip_fetch: false
          skip_checkout: false

      - name: Upload JSON artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-iso-links
          path: windows_iso_links.json
          retention-days: 90
